# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12

variables:
  http_proxy: "$HTTP_PROXY"
  https_proxy: "$HTTPS_PROXY"
  no_proxy: "$NO_PROXY"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.npm

stages:
  - build
  - deploy

# test_async:
#   script:
#    - npm install
#    - node ./specs/start.js ./specs/async.spec.js

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
  tags:
    - docker


pages:
  stage: deploy
  script:
    - mkdir public
    - cp ./dist/* public/
  artifacts:
    paths:
      - public
  tags:
    - docker